@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package iliiasik.artistry.network;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;