@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package iliiasik.artistry.block;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;