plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

if (benchmarkBuild) {
    tasks.named('jar') {
        archiveClassifier = 'benchmark'
    }
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    if (project(':common').file('src/main/resources/META-INF/accesstransformer.cfg').exists()) {
        accessTransformers = [project(':common').file('src/main/resources/META-INF/accesstransformer.cfg').absolutePath]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('forge.enabledGameTestNamespaces', mod_id)
            ideName = "Forge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    annotationProcessor group: 'org.spongepowered', name: 'mixin', version: '0.8.5', classifier: 'processor'
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            'MixinConfigs': "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}
