@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package iliiasik.artistry.client.ui.screen;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;