@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package iliiasik.artistry.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;