@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package iliiasik.artistry.command;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
